[package]
name = "gameboy-emulator-v2"
version = "0.1.0"
authors = ["Anders Conbere <anders@conbere.org>"]
edition = "2018"

[dependencies.sdl2]
  version = "0.34.2"
  default-features = false
  features = ["ttf"]
[dependencies.clap]
  version = "2.33.2"
[dependencies.anyhow]
  version = "1.0.33"
